version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8080 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://user:password@mysql:3306/db_name

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

  